### ISSUE TITLE
访问https API没有数据返回

### ISSUE THREAD

**Issue by GavinZhao8** [cytle/wechat_web_devtools#1]
访问了api接口，https的，虽然发送成功了，但是没有callback

**Comment by cytle** [comment]
您好，控制台有没有打印什么警告

**Comment by colorwin** [comment]
@cytle +1
在没有写appid的时候是回调函数是成功的，写了appid后回调函数没有成功执行。
调试面板的Network 显示https请求显示成功了，并且返回的相关数据。
但页面没有更新，我在里面的回调函数里写语句也没有执行。

调试console界面没有报错信息。
终端有报错信息，但是无论有无appid都有这个报错信息，而没有appid的时候是可以成功回调的。
```
[4896:4896:0522/115046:ERROR:CONSOLE(1588)] "TypeError: Cannot read property 'certificateDetailsPromise' of undefined TypeError: Cannot read property 'certificateDetailsPromise' of undefined
    at r (<anonymous>:1:1116)
    at WebInspector.NetworkManager.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:737:185)
    at WebInspector.NetworkDispatcher.responseReceived (chrome-devtools://devtools/bundled/inspector.js:7384:236)
    at Object.dispatch (chrome-devtools://devtools/bundled/inspector.js:4608:63)
    at WebInspector.MainConnection.dispatch (chrome-devtools://devtools/bundled/inspector.js:4548:31)
    at WebInspector.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/inspector.js:10773:7)
    at WebInspector.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:737:185)
    at innerDispatch (chrome-devtools://devtools/bundled/inspector.js:1588:58)
    at InspectorFrontendAPIImpl._dispatch (chrome-devtools://devtools/bundled/inspector.js:1587:1)
    at DevToolsAPIImpl._dispatchOnInspectorFrontendAPI (devtools_compatibility.js:62:21)
```

**Comment by colorwin** [comment]
勾选“开发环境不校验请求域名，TLS版本以及HTTPS证书”后请求回调成功。

**Comment by colorwin** [comment]
@cytle 这个问题可以跟进一下吗?

**Comment by colorwin** [comment]
微信开发者工具虽然没有, 但是终端下好像会给出一些相应的错误:
```
[5598:5618:0616/170511:ERROR:ssl_client_socket_impl.cc(1146)] handshake failed; returned -1, SSL error code 1, net_error -101
```

**Comment by cytle** [comment]
同issue https://github.com/cytle/wechat_web_devtools/issues/11

**Comment by cytle** [comment]
@GavinZhao8 @colorwin 已经解决

**Comment by colorwin** [comment]
@cytle 辛苦, 感谢
