### ISSUE TITLE
Attempting to require callback on nonexistent surface

### ISSUE THREAD

**Issue by ilovepumpkin** [cytle/wechat_web_devtools#11]
不好意思，我之前的小程序还是不能运行，我用了bluebird, 一直报timeout的错误，命令行窗口也有错误。

命令行窗口报错
```

ilovepumpkin@ruige:~/git/wechat_web_devtools$ ./bin/wxdt 
/home/ilovepumpkin/git/wechat_web_devtools
[7031:7031:0601/201015:ERROR:browser_plugin_guest.cc(444)] Attempting to require callback on nonexistent surface
[7031:7031:0601/201040:ERROR:CONSOLE(1588)] "TypeError: Cannot read property 'certificateDetailsPromise' of undefined TypeError: Cannot read property 'certificateDetailsPromise' of undefined
    at r (<anonymous>:1:1116)
    at WebInspector.NetworkManager.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:737:185)
    at WebInspector.NetworkDispatcher.responseReceived (chrome-devtools://devtools/bundled/inspector.js:7384:236)
    at Object.dispatch (chrome-devtools://devtools/bundled/inspector.js:4608:63)
    at WebInspector.MainConnection.dispatch (chrome-devtools://devtools/bundled/inspector.js:4548:31)
    at WebInspector.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/inspector.js:10773:7)
    at WebInspector.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:737:185)
    at innerDispatch (chrome-devtools://devtools/bundled/inspector.js:1588:58)
    at InspectorFrontendAPIImpl._dispatch (chrome-devtools://devtools/bundled/inspector.js:1587:1)
    at DevToolsAPIImpl._dispatchOnInspectorFrontendAPI (devtools_compatibility.js:62:21)
    at DevToolsAPIImpl.dispatchMessage (devtools_compatibility.js:147:14)", source: chrome-devtools://devtools/bundled/inspector.js (1588)
```
小程序开发工具窗口报错
```
bluebird.min.js [sm]:29 Unhandled rejection (<{"errMsg":"request:fail timeout"}>, no stack trace)
D @ bluebird.min.js [sm]:29
E @ bluebird.min.js [sm]:29
k @ bluebird.min.js [sm]:29
e._notifyUnhandledRejection @ bluebird.min.js [sm]:29
r._drainQueue @ bluebird.min.js [sm]:29
r._drainQueues @ bluebird.min.js [sm]:29
drainQueues @ bluebird.min.js [sm]:29
```

**Comment by sunzongzheng** [comment]
同超时，wx.request一直超时，转到windows下尝试了并不会超时

**Comment by sunzongzheng** [comment]
侧栏菜单-项目-勾选 `开发环境不校验请求域名...`，我这边可以了

**Comment by cytle** [comment]
上次追踪了，可能nw版本不对，我晚上再追踪下，最近公司996，实在没时间看。。

**Comment by cytle** [comment]
已经解决，pull即可

追踪过程可以看我的这篇文章，https://cytle.github.io/2017/06/18/%E8%AE%B0%E4%B8%80%E6%AC%A1debug/
