### ISSUE TITLE
运行后报这个信息

### ISSUE THREAD

**Issue by barray888** [cytle/wechat_web_devtools#12]
`[8663:8663:0612/154639:ERROR:CONSOLE(1588)] "TypeError: Cannot read property 'certificateDetailsPromise' of undefined TypeError: Cannot read property 'certificateDetailsPromise' of undefined
    at r (<anonymous>:1:1116)
    at WebInspector.NetworkManager.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:737:185)
    at WebInspector.NetworkDispatcher.responseReceived (chrome-devtools://devtools/bundled/inspector.js:7384:236)
    at Object.dispatch (chrome-devtools://devtools/bundled/inspector.js:4608:63)
    at WebInspector.MainConnection.dispatch (chrome-devtools://devtools/bundled/inspector.js:4548:31)
    at WebInspector.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/inspector.js:10773:7)
    at WebInspector.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:737:185)
    at innerDispatch (chrome-devtools://devtools/bundled/inspector.js:1588:58)
    at InspectorFrontendAPIImpl._dispatch (chrome-devtools://devtools/bundled/inspector.js:1587:1)
    at DevToolsAPIImpl._dispatchOnInspectorFrontendAPI (devtools_compatibility.js:62:21)", source: chrome-devtools://devtools/bundled/inspector.js (1588)
`

**Comment by cytle** [comment]
这个issue同https://github.com/cytle/wechat_web_devtools/issues/11

**Comment by cytle** [comment]
已经解决，pull即可，同https://github.com/cytle/wechat_web_devtools/issues/11
