### ISSUE TITLE
ubuntu gnome提示如下信息

### ISSUE THREAD

**Issue by edboffical** [cytle/wechat_web_devtools#27]
安装微信开发者工具对应nwjs版本：0.19.4
update nwjs success
[10238:10238:0831/150105:ERROR:browser_main_loop.cc(265)] Gtk: 无法在模块路径中找到主题引擎：“murrine”，
fs.js:854
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/home/edb/.config/微信web开发者工具'
    at Object.fs.mkdirSync (fs.js:854:18)
    at Function.mkdir.sync (/home/edb/wechat_web_devtools/package.nw/node_modules/mkdir-p/index.js:22:8)
    at Function.mkdir.sync (/home/edb/wechat_web_devtools/package.nw/node_modules/mkdir-p/index.js:21:11)
    at init (/home/edb/wechat_web_devtools/package.nw/app/dist/config/dirConfig.js:1:232)
    at Object.<anonymous> (/home/edb/wechat_web_devtools/package.nw/app/dist/config/dirConfig.js:1:980)
    at Module._compile (module.js:595:32)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)

**Comment by cytle** [comment]
- Gtk: 无法在模块路径中找到主题引擎：“murrine”，这问题Google下应该能解决
- Error: EACCES: permission denied, mkdir '/home/edb/.config/微信web开发者工具'，权限问题？

**Comment by edboffical** [comment]
第一个没问题了 但是第二个用sudo权限还不够吗

**Comment by edboffical** [comment]
好吧 sudo su之后再运行就好了

**Comment by cytle** [comment]
删除`/home/edb/.config/微信web开发者工具`, 然后别用`sudo`试下

**Comment by cytle** [comment]
别用sudo安装，clone也用正常权限

**Comment by edboffical** [comment]
可以 又有更新了哈哈 要记得维护项目啊

**Comment by cytle** [comment]
readme有步骤可以自己升级

![image](https://user-images.githubusercontent.com/5120505/29911666-485ab06a-8e61-11e7-9555-34e4216c74d7.png)

兄弟，快来一波pr
