### ISSUE TITLE
本地调试的热更新功能无法正常使用。

### ISSUE THREAD

**Issue by vincentCheng** [cytle/wechat_web_devtools#306]
你好，我使用“微信开发者工具”的“云开发”功能中的“本地调试”的过程中，ctrl+s正常保存我自己的代码，然后出现这样的bug：

`[error] Uncaught Exception:  Error: 函数必须导出名为 'main' 的方法
    at u.load (C:\Program Files (x86)\Tencent\微信web开发者工具\code\package.nw\js\common\cloud-functions-debugger-server\worker\node.js:1:22007)
    at u.reload (C:\Program Files (x86)\Tencent\微信web开发者工具\code\package.nw\js\common\cloud-functions-debugger-server\worker\node.js:1:26848)
    at C:\Program Files (x86)\Tencent\微信web开发者工具\code\package.nw\js\common\cloud-functions-debugger-server\worker\node.js:1:28280
    at process.<anonymous> (C:\Program Files (x86)\Tencent\微信web开发者工具\code\package.nw\js\common\cloud-functions-debugger-server\worker\node.js:1:28356)
    at process.emit (events.js:203:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)`

这是调试信息：
[2020-06-20 10:40:50.591] [INFO] [\core.wxvpkg\bc78839ccca8df9e5ceeb7fae11b7be2.js] store.js rehydration finished
[2020-06-20 10:40:52.302] [INFO] [\core.wxvpkg\8e433dffaa20c3a7331f9aeecb1221b0.js] ready to enable network transport
[2020-06-20 10:40:52.303] [INFO] [\core.wxvpkg\8e433dffaa20c3a7331f9aeecb1221b0.js] enable network transport
[2020-06-20 10:40:52.320] [INFO] [\core.wxvpkg\8e433dffaa20c3a7331f9aeecb1221b0.js] init open arg:  -load-extension=C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\1a695ca2de1a85735f93a43fb366c83f\WeappPlugin
[2020-06-20 10:40:52.321] [INFO] [\core.wxvpkg\8e433dffaa20c3a7331f9aeecb1221b0.js] init open arg:  --user-data-dir=C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\1a695ca2de1a85735f93a43fb366c83f
[2020-06-20 10:40:53.729] [ERROR] [\core.wxvpkg\15ba1827c7f6564a45df6bd44da3a977.js] https://servicewechat.com/wxa-dev-cloud/getcosinfo?hook=tgit Error: 未授权腾讯云, [20200620 10:40:53][wx54b07af1c18c9395]
[2020-06-20 10:40:58.895] [INFO] [\core.wxvpkg\6ec1bd15f70b3ac0c6b44da80b0fe6c6.js] [performance] [warn] too long after the listener is register, cannot mark simulator paint: 5192ms
[2020-06-20 10:50:31.954] [INFO] [\core.wxvpkg\b8662f5f8bb2f4761de7ff3f123beefd.js] Launch debugger success
[2020-06-20 10:55:55.391] [INFO] [\core.wxvpkg\b8662f5f8bb2f4761de7ff3f123beefd.js] found scfdebug window state is closed, stopping...
[2020-06-20 10:58:33.298] [INFO] [\core.wxvpkg\b8662f5f8bb2f4761de7ff3f123beefd.js] Launch debugger success

请问该怎么办？
是不是这个错误“Error: 未授权腾讯云” 导致的？

我使用的版本是：
Stable v1.03.2005140

我之前使用了别的版本，没有出现过这个问题，卸载并且重新装了这个版本的程序就有这个问题了。

**Comment by hmd3922** [comment]
你是怎么更新到1.03的，我总是更新不成功。。。。。。。
