### ISSUE TITLE
运行出现报错

### ISSUE THREAD

**Issue by Sweetmile** [cytle/wechat_web_devtools#38]
系统为Ubuntu 17.04
过程中使用了全部使用了sudo
目录已给777权限
在root账号下可以打开
以下为报错全文

```
fs.js:854
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/home/xyzhao/.config/微信web开发者工具'
    at Object.fs.mkdirSync (fs.js:854:18)
    at Function.mkdir.sync (/home/xyzhao/wechat_web_devtools/package.nw/node_modules/mkdir-p/index.js:22:8)
    at Proxy.mkdir.sync (/home/xyzhao/wechat_web_devtools/package.nw/node_modules/mkdir-p/index.js:21:11)
    at /home/xyzhao/wechat_web_devtools/package.nw/js/92320c1386e6db6a6f2556736a9bc280.js:1:279
    at Object.<anonymous> (/home/xyzhao/wechat_web_devtools/package.nw/js/92320c1386e6db6a6f2556736a9bc280.js:1:958)
    at Module._compile (module.js:595:32)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)

```

**Comment by Sweetmile** [comment]
抱歉 已经解决 解决方案是
在root账号下卸载 然后 删除 .cache 和 tmp 中的 对于文件夹
再正常安装

表示 再也不敢乱用sudo (萌新前来报道。。
