### ISSUE TITLE
无法使用console

### ISSUE THREAD

**Issue by jmkylvy** [cytle/wechat_web_devtools#40]
Chrome devtools的console无法正常使用。
如输入命令后没有反馈、无法查看错误信息详情

**Comment by jmkylvy** [comment]
@cytle 
就是在console中无论输入什么都没有变化。。。
![console](http://7xjb1c.com1.z0.glb.clouddn.com/20171018.gif)
Fedora26

**Comment by cytle** [comment]
无法帮到你，你可以自助debug，看看报错
  1. 运行`./bin/wxdt debug`
  2. 打开`http://localhost:9222/`下的`_generated_background_page.html`页面如下图

![image](https://user-images.githubusercontent.com/5120505/31776431-237977f6-b4b1-11e7-9b5f-8c4cce7ed451.png)

进去就是`js`调试，如有问题发上来一块讨论哈～

**Comment by jmkylvy** [comment]
./bin/wxdt debug打开之后使用console在终端会报错和Issues#41 报的错一样。。 
ReferenceError: SDK is not defined
    at DevToolsAPIImpl.DevToolsAPI.sendMessageToEmbedder (<anonymous>:1:5417)
    at InspectorFrontendHostImpl.inspectedURLChanged (devtools_compatibility.js:492:21)
    at WebInspector.Target.setInspectedURL (chrome-devtools://devtools/bundled/inspector.js:4660:23)
    at WebInspector.ResourceTreeModel._frameNavigated (chrome-devtools://devtools/bundled/inspector.js:7138:15)
    at WebInspector.PageDispatcher.frameNavigated (chrome-devtools://devtools/bundled/inspector.js:7232:26)
    at Object.dispatch (chrome-devtools://devtools/bundled/inspector.js:4608:63)
    at WebInspector.MainConnection.dispatch (chrome-devtools://devtools/bundled/inspector.js:4548:31)
    at WebInspector.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/inspector.js:10773:7)
    at WebInspector.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:737:185)
    at innerDispatch (chrome-devtools://devtools/bundled/inspector.js:1588:58)", source: chrome-devtools://devtools/bundled/inspector.js (1588)

还有就是调试的页面啥都没，全部页面点进去都是空的

**Comment by YanYuanFE** [comment]
小程序调试console没有问题，公众号console没有输出@cytle，希望能修复下，不然没法用了，可以回退上一个版本吗

**Comment by cytle** [comment]
可以尝试下，git 切版本到tag: v1.01.170925

**Comment by YanYuanFE** [comment]
v1的都不行，我切到0.19了

**Comment by cytle** [comment]
@jmkylvy @YanYuanFE @aiwhj 升级`nw.js`解决问题了，并且开发者工具升级到了最新版，`git pull`即可
