### ISSUE TITLE
SDK is not defined 

### ISSUE THREAD

**Issue by skunight** [cytle/wechat_web_devtools#41]
[20223:20223:1018/105001:ERROR:CONSOLE(1588)] "ReferenceError: SDK is not defined ReferenceError: SDK is not defined
    at DevToolsAPIImpl.DevToolsAPI.sendMessageToEmbedder (<anonymous>:1:5417)
    at InspectorFrontendHostImpl.inspectedURLChanged (devtools_compatibility.js:492:21)
    at WebInspector.Target.setInspectedURL (chrome-devtools://devtools/bundled/inspector.js:4660:23)
    at WebInspector.ResourceTreeModel._processCachedResources (chrome-devtools://devtools/bundled/inspector.js:7115:170)
    at callback (chrome-devtools://devtools/bundled/inspector.js:4588:39)
    at Object.dispatchResponse (chrome-devtools://devtools/bundled/inspector.js:4595:10)
    at WebInspector.MainConnection.dispatch (chrome-devtools://devtools/bundled/inspector.js:4545:60)
    at WebInspector.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/inspector.js:10773:7)
    at WebInspector.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:737:185)
    at innerDispatch (chrome-devtools://devtools/bundled/inspector.js:1588:58)", source: chrome-devtools://devtools/bundled/inspector.js (1588)

**Comment by cytle** [comment]
对实际使用有影响吗？没有影响一般不处理

**Comment by skunight** [comment]
微信js加载不到,基本上就是微信功能没法用,而且看不到console里面error报错

**Comment by YanYuanFE** [comment]
console无法打印输出，可能是这个影响了

**Comment by cytle** [comment]
同 https://github.com/cytle/wechat_web_devtools/issues/40 升级`nw.js`解决问题了，并且开发者工具升级到了最新版，`git pull`即可
