### ISSUE TITLE
启动工具后终端报错,sensor页面缺失

### ISSUE THREAD

**Issue by sausager** [cytle/wechat_web_devtools#9]
本人使用deepin 15.4系统,
安装好工具后,使用 alias 自定义命令 [alias wcdt="cd /opt/tencent/wechat_web_devtools/ && ./bin/wxdt"] 启动工具,发现终端有如下报错:
[16563:16563:0526/152104:ERROR:browser_plugin_guest.cc(444)] Attempting to require callback on nonexistent surface

然后发现了Sensor功能页面缺失,如图:
![20170526152449](https://cloud.githubusercontent.com/assets/16453836/26484999/b1629dc4-4227-11e7-9e08-606e0702f7b3.png)

关闭工具之后终端追加报错如下:
[16563:16563:0526/152105:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
[16563:16563:0526/152111:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'style' of null", source:  (1)
extensions::guestViewContainer:276
    var internal = privates(this).internal;
                                 ^

TypeError: Cannot read property 'internal' of undefined
    at HTMLElement.proto.focus (extensions::guestViewContainer:276:34)
    at Timeout._onTimeout (/opt/tencent/wechat_web_devtools/package.nw/app/dist/components/edit/edit.js:1:7669)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

请问有办法修复吗?

**Comment by cytle** [comment]
已经修复，更新为最新master即可
